#!/usr/bin/env python3
"""
Compare threaded encoder output with non-threaded run_encoder.cc output
"""

import numpy as np
import sys

def compare_logits(threaded_file, run_encoder_file):
    """Compare two logit files frame by frame"""
    
    print("=" * 60)
    print("Comparing Threaded vs Non-Threaded run_encoder.cc")
    print("=" * 60)
    print()
    
    # Load files
    print(f"Loading threaded output: {threaded_file}")
    threaded = np.load(threaded_file)
    print(f"  Shape: {threaded.shape}")
    
    print(f"Loading run_encoder output: {run_encoder_file}")
    run_encoder = np.load(run_encoder_file)
    print(f"  Shape: {run_encoder.shape}")
    print()
    
    # Remove batch dimension if present
    if len(threaded.shape) == 3:
        threaded = threaded[0]
    if len(run_encoder.shape) == 3:
        run_encoder = run_encoder[0]
    
    # Check shapes match
    if threaded.shape != run_encoder.shape:
        print(f"❌ ERROR: Shape mismatch!")
        print(f"  Threaded: {threaded.shape}")
        print(f"  run_encoder: {run_encoder.shape}")
        return False
    
    num_frames, num_logits = threaded.shape
    print(f"Comparing {num_frames} frames, {num_logits} logits per frame")
    print()
    
    # Compare frame by frame
    all_match = True
    max_diff_overall = 0.0
    
    # Group frames into chunks for reporting
    chunk_size = 10
    num_chunks = (num_frames + chunk_size - 1) // chunk_size
    
    for chunk_idx in range(num_chunks):
        start_frame = chunk_idx * chunk_size
        end_frame = min(start_frame + chunk_size, num_frames)
        
        chunk_threaded = threaded[start_frame:end_frame]
        chunk_run_encoder = run_encoder[start_frame:end_frame]
        
        # Calculate differences
        diff = np.abs(chunk_threaded - chunk_run_encoder)
        max_diff = np.max(diff)
        mean_diff = np.mean(diff)
        
        max_diff_overall = max(max_diff_overall, max_diff)
        
        # Check if chunk matches
        matches = max_diff < 1e-5
        status = "✅" if matches else "⚠️ "
        
        print(f"{status} Chunk {chunk_idx + 1:2d} (frames {start_frame:3d}-{end_frame-1:3d}): "
              f"max_diff={max_diff:8.5f}, mean_diff={mean_diff:8.5f}")
        
        if not matches:
            all_match = False
            # Show details for mismatched frames
            for i in range(end_frame - start_frame):
                frame_idx = start_frame + i
                frame_diff = np.abs(threaded[frame_idx] - run_encoder[frame_idx])
                frame_max_diff = np.max(frame_diff)
                if frame_max_diff >= 1e-5:
                    print(f"     Frame {frame_idx:3d}: max_diff={frame_max_diff:8.5f}")
    
    print()
    print("=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"Total frames: {num_frames}")
    print(f"Maximum difference: {max_diff_overall:.6f}")
    
    if all_match:
        print("✅ All frames match perfectly! (max_diff < 1e-5)")
        return True
    else:
        print("⚠️  Some frames have differences")
        if max_diff_overall < 0.001:
            print("   But differences are very small (< 0.001), acceptable for float32")
        return False

if __name__ == "__main__":
    threaded_file = "build/streaming_fbank_30ms_threaded_logits.npy"
    run_encoder_file = "build/run_encoder_with_threaded_fbank.npy"
    
    print("Note: Comparing with run_encoder output using the SAME FBank features")
    print("      (generated by threaded version)")
    print()
    
    success = compare_logits(threaded_file, run_encoder_file)
    sys.exit(0 if success else 1)
